apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: acm-dev-catalog-custom
  namespace: openshift-marketplace
spec:
  displayName: Custom Catalog Source
  publisher: Red Hat
  sourceType: grpc
  image:
  updateStrategy:
    registryPoll:
      interval: 10m
